### ISSUE TITLE
can't install on 0.11.13

### ISSUE THREAD

**Issue by zheng1** [egorFiNE/node-compress-buffer#13]
```
> compress-buffer@1.2.2 install /Volumes/data/work/proxy/node_modules/compress-buffer
> node-gyp rebuild

  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/ioapi.o
  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/unzip.o
../deps/zlib/contrib/minizip/unzip.c:1250:46: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if ((pfile_in_zip_read_info->read_buffer == NULL))
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../deps/zlib/contrib/minizip/unzip.c:1250:46: note: remove extraneous parentheses around the comparison to silence this warning
    if ((pfile_in_zip_read_info->read_buffer == NULL))
        ~                                    ^      ~
../deps/zlib/contrib/minizip/unzip.c:1250:46: note: use '=' to turn this equality comparison into an assignment
    if ((pfile_in_zip_read_info->read_buffer == NULL))
                                             ^~
                                             =
1 warning generated.
  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/zip.o
../deps/zlib/contrib/minizip/zip.c:765:15: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if ((level==2))
         ~~~~~^~~
../deps/zlib/contrib/minizip/zip.c:765:15: note: remove extraneous parentheses around the comparison to silence this warning
    if ((level==2))
        ~     ^  ~
../deps/zlib/contrib/minizip/zip.c:765:15: note: use '=' to turn this equality comparison into an assignment
    if ((level==2))
              ^~
              =
../deps/zlib/contrib/minizip/zip.c:767:15: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if ((level==1))
         ~~~~~^~~
../deps/zlib/contrib/minizip/zip.c:767:15: note: remove extraneous parentheses around the comparison to silence this warning
    if ((level==1))
        ~     ^  ~
../deps/zlib/contrib/minizip/zip.c:767:15: note: use '=' to turn this equality comparison into an assignment
    if ((level==1))
              ^~
              =
../deps/zlib/contrib/minizip/zip.c:196:12: warning: unused function 'free_linkedlist' [-Wunused-function]
local void free_linkedlist(ll)
           ^
3 warnings generated.
  CC(target) Release/obj.target/zlib/deps/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/zlib/compress.o
  CC(target) Release/obj.target/zlib/deps/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzio.o
  CC(target) Release/obj.target/zlib/deps/zlib/infback.o
  CC(target) Release/obj.target/zlib/deps/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/zlib/inflate.o
  CC(target) Release/obj.target/zlib/deps/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/deps/zlib/zutil.o
  LIBTOOL-STATIC Release/chrome_zlib.a
  CXX(target) Release/obj.target/compress_buffer_bindings/src/compress-buffer.o
../src/compress-buffer.cc:24:49: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::Error(String::New(what)));
                                               ~~~~~~~~^
../src/compress-buffer.cc:27:30: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> compress(const Arguments& args) {
                             ^~~~~~~~~
                             v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/compress-buffer.cc:28:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/compress-buffer.cc:34:10: error: member access into incomplete type 'const v8::internal::Arguments'
        if (args.Length() < 1) {
                ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/compress-buffer.cc:35:10: error: no matching function for call to 'Undefined'
                return Undefined();
                       ^~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/compress-buffer.cc:38:31: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        if (!Buffer::HasInstance(args[0])) {
                                 ~~~~^~
../src/compress-buffer.cc:40:10: error: no matching function for call to 'Undefined'
                return Undefined();
                       ^~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/compress-buffer.cc:43:29: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        Local<Object> bufferIn=args[0]->ToObject();
                               ~~~~^~
../src/compress-buffer.cc:49:10: error: member access into incomplete type 'const v8::internal::Arguments'
        if (args.Length() > 1) {
                ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/compress-buffer.cc:50:26: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                compressionLevel = args[1]->IntegerValue();
                                   ~~~~^~
../src/compress-buffer.cc:79:10: error: no matching function for call to 'Undefined'
                return Undefined();
                       ^~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/compress-buffer.cc:85:2: error: unexpected namespace name 'Buffer': expected expression
        Buffer *BufferOut=Buffer::New(bufferOut, bytesCompressed);
        ^
../src/compress-buffer.cc:85:10: error: use of undeclared identifier 'BufferOut'; did you mean 'bufferOut'?
        Buffer *BufferOut=Buffer::New(bufferOut, bytesCompressed);
                ^~~~~~~~~
                bufferOut
../src/compress-buffer.cc:66:8: note: 'bufferOut' declared here
        char *bufferOut=(char*) malloc(bytesCompressed);
              ^
../src/compress-buffer.cc:93:15: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(BufferOut->handle_);
               ~~~~~ ^
../src/compress-buffer.cc:93:21: error: use of undeclared identifier 'BufferOut'; did you mean 'bufferOut'?
        return scope.Close(BufferOut->handle_);
                           ^~~~~~~~~
                           bufferOut
../src/compress-buffer.cc:66:8: note: 'bufferOut' declared here
        char *bufferOut=(char*) malloc(bytesCompressed);
              ^
../src/compress-buffer.cc:93:30: error: member reference base type 'char' is not a structure or union
        return scope.Close(BufferOut->handle_);
                           ~~~~~~~~~^ ~~~~~~~
../src/compress-buffer.cc:97:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> uncompress(const Arguments &args) {
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/compress-buffer.cc:98:10: error: member access into incomplete type 'const v8::internal::Arguments'
        if (args.Length() < 1) {
                ^
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/compress-buffer.cc:99:10: error: no matching function for call to 'Undefined'
                return Undefined();
                       ^~~~~~~~~
/Users/zheng1/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/compress_buffer_bindings/src/compress-buffer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/data/work/proxy/node_modules/compress-buffer
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
```

**Comment by stephanos** [comment]
Me neither.

**Comment by denisbetsi** [comment]
Looks like the original creators gave up on this about 2 years ago

**Comment by egorFiNE** [comment]
Not exactly, the last update was a year ago. However this project is indeed depricated since node has sync compression routines for long time already.

**Comment by slang800** [comment]
you can officially deprecate it using this: https://docs.npmjs.com/cli/deprecate

**Comment by egorFiNE** [comment]
@slang800 oh thanks, did not know about this one. I will deprecate this package.
